name: PiiHide - Build & Test

on: 
  push:
    branches-ignore:
      - master

jobs:
  build-and-test:
    name: build & test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./

      - name: Run unit tests
        run: dotnet test --configuration Release
        working-directory: ./