name: PiiHide - Build & Test

on: 
  push:
    branches-ignore:
      - master

jobs:
  build-and-test:
    name: build & test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      # Tool Restore
      - name: Tool Restore
        run: dotnet tool restore
        working-directory: ./
      
      # Build
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./

      # Test
      - name: Run unit tests
        run: dotnet test --configuration Release
        working-directory: ./